### ISSUE TITLE
More prose revisions

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/A_Little_Adventure#2]
A lot of the dialogue still has a non-native feel to it; I might want to do another copyediting/rewriting pass... 
Edit: this includes breaking up walls of text

**Comment by cooljeanius** [comment]
cc @max-torch

**Comment by max-torch** [comment]
What's the latest version of wesnoth this runs on?

**Comment by cooljeanius** [comment]
> What's the latest version of wesnoth this runs on?

I'm working on porting it from 1.14 to 1.16 currently; it runs on 1.16, but I haven't uploaded it to the 1.16 add-on server yet, because I'm not done testing...

**Comment by cooljeanius** [comment]
ok, *now* it's on the 1.16 add-on server

**Comment by cooljeanius** [comment]
@MultiSeptim you may want to pay attention to this in case I make any further progress on it

**Comment by cooljeanius** [comment]
> @MultiSeptim you may want to pay attention to this in case I make any further progress on it

@celerini you too

**Comment by cooljeanius** [comment]
one thing I need to decide: whether to always consistently capitalize "Nereids" or not

**Comment by celerini** [comment]
I would prefer to not capitalize them, at least in Czech.

These are definitely not daughters of Nereus, but they are [nereids](https://en.wikipedia.org/wiki/Nereids#Modern_use) as mermaids, merfolk or saurians.

However, I didn't play ALA yet, nor read the whole story. And I'm not into English grammar to advise you whether or when to capitalize them.

In Czech we would capitalize them if they are family or nation.

**Comment by cooljeanius** [comment]
PRs #23 and #24 addressed this a bit

**Comment by MultiSeptim** [comment]
Please, regenerate po[t]file[s] too.

**Comment by cooljeanius** [comment]
> Please, regenerate po[t]file[s] too.

yeah, once I get a chance (busy with other stuff today)

**Comment by MultiSeptim** [comment]
Still remaining.

**Comment by cooljeanius** [comment]
> Still remaining.

@MultiSeptim Check again now, after [402dfc0](https://github.com/cooljeanius/A_Little_Adventure/commit/402dfc0dee44c69d2dafc6bb7b42ab6cad6921ac)?

**Comment by cooljeanius** [comment]
Depends on #22

**Comment by cooljeanius** [comment]
> Depends on #22

OK that's fixed now...

@celerini are you available to take another look?

**Comment by celerini** [comment]
Here I am. Look at what? Your Czech translation of Japanese translation looks good.

Do you want me instead of @MultiSeptim to translate Glauco ranking and (for Czech declension unfortunate) an addition of the $trapper_name?

**Comment by cooljeanius** [comment]
> Here I am. Look at what? Your Czech translation of Japanese translation looks good.
> 
> Do you want me instead of @MultiSeptim to translate Glauco ranking and (for Czech declension unfortunate) an addition of the $trapper_name?

I'm actually not quite sure what I meant now; I think I was referring back a few comments to whatever it was @MultiSeptim said "Still remaining" about...

**Comment by cooljeanius** [comment]
Note that @k-konami may want to update the Japanese translation more, which may require updating the English more (although I'm going to be away for the next week, so I won't be able to review it until later)...

**Comment by k-konami** [comment]
> Note that @k-konami may want to update the Japanese translation more, which may require updating the English more (although I'm going to be away for the next week, so I won't be able to review it until later)...

If you still plan to make more changes to the English text, I would like to do the Japanese translation after that is done. I don't want you to work in a hurry. I will wait until the changes to the English text are completed. Don't worry about it.

**Comment by MultiSeptim** [comment]
Just regenerate po(t) file(s) after it (after all the suggested changes) and I will make my part of the work. So, don't worry even from my side.

**Comment by cooljeanius** [comment]
anything left to do here?

**Comment by cooljeanius** [comment]
I'm guessing now that I've merged #30, that I can close this...

**Comment by cooljeanius** [comment]
Actually I'm going to reopen this; some of those walls of texts still need to be broken up...

**Comment by cooljeanius** [comment]
One other thing that fits here: the whole "Est" vs. "East" confusion. "East" is the direction, but when part of the name "Estmark Hills" it's "Est"... so when the word is seen standalone in places, how to tell whether it's referring to the hills or the direction?

**Comment by cooljeanius** [comment]
cc @knyghtmare

**Comment by celerini** [comment]
As far as I know, the Est means East, Estmark means eastern border and Estmark Hills are [the hills of the eastern border](https://github.com/wesnoth/wesnoth/blob/128c0dacf9ff44a0158b18ce12770e6b7ae49857/data/campaigns/The_Hammer_of_Thursagan/scenarios/03_Strange_Allies.cfg#L21). So I would generally take Est as East until a context shows something different.

**Comment by cooljeanius** [comment]
> As far as I know, the Est means East, Estmark means eastern border and Estmark Hills are [the hills of the eastern border](https://github.com/wesnoth/wesnoth/blob/128c0dacf9ff44a0158b18ce12770e6b7ae49857/data/campaigns/The_Hammer_of_Thursagan/scenarios/03_Strange_Allies.cfg#L21). So I would generally take Est as East until a context shows something different.

So should Amoran's designation as "the last town toward Est" actually be "the last town toward the Estmark Hills" or "the last town toward the east"?

**Comment by MultiSeptim** [comment]
The last town toward the east wild is best in my opinion.

**Comment by cooljeanius** [comment]
I went with a slightly different wording for that signpost in [80ac90b](https://github.com/cooljeanius/A_Little_Adventure/commit/80ac90b008f1fefb3c2401e1ae7699b4ad26d20c); this issue remains open for the breaking up of the walls of text...

**Comment by MultiSeptim** [comment]
Fine for me.

**Comment by cooljeanius** [comment]
I'm probably going to cut a new release soon; if you'd like to see any more prose revisions before then, please let me know within the next 24 hours or so. (The breaking up of the walls of text probably won't make it into this next release, as I just don't feel like doing that now)

**Comment by cooljeanius** [comment]
> I'm probably going to cut a new release soon; if you'd like to see any more prose revisions before then, please let me know within the next 24 hours or so. (The breaking up of the walls of text probably won't make it into this next release, as I just don't feel like doing that now)

ok [4.1.7](https://github.com/cooljeanius/A_Little_Adventure/releases/tag/4.1.7) released

**Comment by cooljeanius** [comment]
This issue has probably gone on long enough to be closeable now; if there are still issues requiring prose revisions, they can have separate issues opened for them.
