### ISSUE TITLE
Update Italian translation

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/A_Little_Adventure#44]
I think I've seen Argesilao on GitHub recently as @argesilao2; maybe he can return to this campaign briefly to update its Italian translation?

**Comment by Argesilao2** [comment]
I'll take a look.

    Il martedì 16 gennaio 2024 alle ore 02:16:41 CET, Eric Gallager ***@***.***> ha scritto:  
 
 


I think I've seen Argesilao on GitHub recently as @Argesilao2; maybe he can return to this campaign briefly to update its Italian translation?

**Comment by Argesilao2** [comment]
I attach the .po file with the Italian translation.I used the most recent campaign version.Write to me at this email if there are any problems.greetings
    Il martedì 16 gennaio 2024 alle ore 21:27:11 CET, Argesilao Argesilao ***@***.***> ha scritto:  
 
  I'll take a look.

    Il martedì 16 gennaio 2024 alle ore 02:16:41 CET, Eric Gallager ***@***.***> ha scritto:  
 
 


I think I've seen Argesilao on GitHub recently as @Argesilao2; maybe he can return to this campaign briefly to update its Italian translation?

**Comment by cooljeanius** [comment]
GitHub filters attachments and email addresses from issue replies received via email...

**Comment by cooljeanius** [comment]
> GitHub filters attachments and email addresses from issue replies received via email...

@Argesilao2 could you try emailing it to egall`@`gwmail`.`gwu`.`edu instead?
